# Generated by Django 5.2.12 on 2026-04-04 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True, verbose_name='客户编号')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('country', models.CharField(max_length=50, verbose_name='国家/地区')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('credit_rating', models.CharField(default='B级 (良好)', max_length=20, verbose_name='信用评级')),
                ('total_trade_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累计交易额($)')),
                ('default_count', models.IntegerField(default=0, verbose_name='历史违约次数')),
            ],
        ),
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=50, unique=True, verbose_name='出口批次号')),
                ('loading_date', models.DateField(verbose_name='装柜时间')),
                ('bol_number', models.CharField(max_length=100, verbose_name='提单号')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('customs_status', models.CharField(default='草稿/待申报', max_length=20, verbose_name='报关状态')),
                ('release_status', models.CharField(default='待放单', max_length=20, verbose_name='放单状态')),
            ],
        ),
        migrations.CreateModel(
            name='FarmBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_batch_id', models.CharField(max_length=50, unique=True, verbose_name='养殖批次号')),
                ('breeding_unit', models.CharField(max_length=50, verbose_name='养殖单元')),
                ('stocking_date', models.DateField(verbose_name='放养日期')),
                ('feed_med_logs', models.TextField(verbose_name='饲料/药物记录')),
                ('target_spec', models.CharField(default='待定', max_length=100, verbose_name='目标规格')),
                ('status', models.CharField(default='养殖中', max_length=20, verbose_name='当前状态')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='责任人')),
            ],
        ),
        migrations.CreateModel(
            name='ExportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_file', models.FileField(blank=True, null=True, upload_to='final_archives/', verbose_name='最终单证压缩包')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('export_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_archive', to='traceability.exportbatch')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_id', models.CharField(max_length=50, unique=True, verbose_name='收获编号')),
                ('harvest_date', models.DateField(verbose_name='起捕日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量(kg)')),
                ('farm_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceability.farmbatch', verbose_name='关联养殖批次')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=50, unique=True, verbose_name='加工批次号')),
                ('factory_name', models.CharField(max_length=100, verbose_name='加工厂名称')),
                ('temp_control', models.TextField(verbose_name='温控记录')),
                ('sample_id', models.CharField(default='未留样', max_length=50, verbose_name='留样编号')),
                ('harvest_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceability.harvestbatch', verbose_name='关联收获批次')),
            ],
        ),
        migrations.AddField(
            model_name='exportbatch',
            name='process_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceability.processbatch', verbose_name='关联加工批次'),
        ),
        migrations.CreateModel(
            name='DocPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='检测报告', max_length=50, verbose_name='文件类型')),
                ('file', models.FileField(null=True, upload_to='evidences/%Y/%m/', verbose_name='证据文件')),
                ('version', models.CharField(default='V1.0', max_length=10, verbose_name='版本号')),
                ('status', models.CharField(default='待审核', max_length=20, verbose_name='文件状态')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('uploader', models.CharField(blank=True, max_length=50, null=True, verbose_name='上传人')),
                ('export_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traceability.exportbatch', verbose_name='关联出口批次')),
                ('farm_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traceability.farmbatch', verbose_name='关联养殖批次')),
                ('process_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traceability.processbatch', verbose_name='关联加工批次')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='下单日期')),
                ('product_spec', models.CharField(max_length=100, verbose_name='需求规格')),
                ('quantity', models.IntegerField(verbose_name='订单数量(kg)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额(FOB)')),
                ('deposit_status', models.CharField(default='未收定金', max_length=20, verbose_name='定金状态')),
                ('status', models.CharField(default='生产准备中', max_length=20, verbose_name='订单状态')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traceability.customer', verbose_name='关联采购商')),
            ],
        ),
        migrations.AddField(
            model_name='exportbatch',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traceability.salesorder', verbose_name='关联贸易订单'),
        ),
    ]
