# Generated by Django 5.2.12 on 2026-04-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总营收(FOB)')),
                ('farm_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='一产养殖成本(饲料/动保)')),
                ('process_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='二产加工成本(包装/冷藏)')),
                ('export_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='三产出海成本(报关/海运)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='净利润')),
                ('status', models.CharField(default='待核算', max_length=20, verbose_name='核算状态')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traceability.salesorder', verbose_name='关联订单')),
            ],
        ),
    ]
