# Generated by Django 5.2.12 on 2026-04-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_financialledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=50, unique=True, verbose_name='单证编号')),
                ('doc_type', models.CharField(choices=[('合同', '销售合同 (Sales Contract)'), ('发票', '商业发票 (Commercial Invoice)'), ('装箱单', '装箱单 (Packing List)'), ('提单', '海运提单 (Bill of Lading)'), ('原产地证', '原产地证 (Cert of Origin)')], max_length=20, verbose_name='单证类型')),
                ('status', models.CharField(default='待签发', max_length=20, verbose_name='单证状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceability.salesorder', verbose_name='关联订单')),
            ],
        ),
    ]
