# Generated by Django 5.2.12 on 2026-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0003_tradedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='financial_status',
            field=models.CharField(default='待收尾款', max_length=20, verbose_name='财务状态'),
        ),
    ]
